/*
 * Estrava
 *
 * Cool Estrava tings
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/jestradaramos/quick-dash/go"
)

func main() {
	log.Printf("Server started")

	RunsApiService := openapi.NewRunsApiService()
	RunsApiController := openapi.NewRunsApiController(RunsApiService)

	UsersApiService := openapi.NewUsersApiService()
	UsersApiController := openapi.NewUsersApiController(UsersApiService)

	router := openapi.NewRouter(RunsApiController, UsersApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
