/*
 * Estrava
 *
 * Cool Estrava tings
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// RunsApiService is a service that implements the logic for the RunsApiServicer
// This service should implement the business logic for every endpoint for the RunsApi API.
// Include any external packages or services that will be required by this service.
type RunsApiService struct {
}

// NewRunsApiService creates a default api service
func NewRunsApiService() RunsApiServicer {
	return &RunsApiService{}
}

// RunGet - 
func (s *RunsApiService) RunGet(ctx context.Context, username string, title string, date string) (ImplResponse, error) {
	// TODO - update RunGet with the required logic for this service method.
	// Add api_runs_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("RunGet method not implemented")
}

// RunPost - 
func (s *RunsApiService) RunPost(ctx context.Context, runGetRequest RunGetRequest) (ImplResponse, error) {
	// TODO - update RunPost with the required logic for this service method.
	// Add api_runs_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("RunPost method not implemented")
}

// TestingGet - 
func (s *RunsApiService) TestingGet(ctx context.Context, username string, title string, date string) (ImplResponse, error) {
	// TODO - update TestingGet with the required logic for this service method.
	// Add api_runs_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("TestingGet method not implemented")
}

// TestingPost - 
func (s *RunsApiService) TestingPost(ctx context.Context, runGetRequest RunGetRequest) (ImplResponse, error) {
	// TODO - update TestingPost with the required logic for this service method.
	// Add api_runs_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("TestingPost method not implemented")
}
