openapi: 3.0.0
info: 
  version: 1.0.0
  title: Estrava
  description: Cool Estrava tings

tags:
- name: "users"
- name: "runs"

paths:
  /user:
    post: 
      tags:
        - "users"
      requestBody: 
        required: true
        content:
          applications/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                password: 
                  type: string
              required: 
                - name
                - username
                - password
      responses:
          201: 
            description: Made new account
          409:
            description: User already exists
          500:
            description: Internal API no workey
          418: 
            description: Teapot!

  /run:
    post: 
      tags:
        - "runs"
      requestBody: 
        required: true
        content:
          applications/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                username:
                  type: string
                distance: 
                  type: number
                time:
                  type: string
                  format: date-time
                date:
                  type: string
                  format: date
              required: 
                - name
                - username
                - distance
                - time
                - date
      responses:
          201: 
            description: Created new run
          400:
            description: Error no bueno
          500:
            description: Internal API no workey
    get: 
      tags:
        - "runs"
      parameters:
        - in: query
          name: title 
          schema:
            type: string
        - in: query
          name: date
          schema: 
            type: string
        - in : query
          name: username
          required: true
          schema:
            type: string
          
      responses:
        200: 
          description: Found runs
        404: 
          description: No content
        500:
          description: Internal API error


components:
  schemas:
    Users:
      type: object
      properties:
        name:
          type: string
        username:
          type: string
        password:
          type: string
    Run: 
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        username:
          type: string
        distance:
          type: number
        time:
          type: string
        date:
          type: string

