openapi: 3.0.0
info: 
  version: 1.0.0
  title: Quick Dash
  description: API that the dashboard will be able to use
paths:
  /weather:
    get:
      description: "Get current weather data"
      responses:
        200:
          description: Weather data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Weather'


        400:
          description: No bueno
          
  /dressmyrun: 
    get:
      description: "Gets appropriate atire for runs"
      responses: 
        200:
          description: dressmyrun

components:
  schemas:
    Weather: 
      type: object
      properties:
        temp: 
          type: integer
          format: int32
        wind: 
          $ref: '#/components/schemas/Wind'
    Wind:
      type: object
      properties: 
        speed:
          type: integer
          format: int32
        direction:
          type: integer
        
  